name = "spinogambino-bet-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-bet.fr"
HMAC_KEY = "55200757354824d2644a41a8fed98585201f1d04442e40d71a51a30233f3c4a4"
COOKIE_NAME = "lto"
PLAY_PATH = "go"
BUTTON_ID = "p5d19e0d538014bcb4ba01ef345d05b6e"
GATE_SALT = "ac42c94e7dfd21e2"
